---
abstract: 'Provide a simple ->DOES override'
author:
  - 'Ben Morrow <ben@morrow.me.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-DOES
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '1.00'
  Test::More: '0.45'
  perl: '5.006001'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-DOES
  repository: http://github.com/mauzo/Class-DOES
version: '1.01'
